### ISSUE TITLE
Strapper 초기화시 소음 발생 건

### ISSUE THREAD

**Issue by ryujunsang** [ryujunsang/K6_Strapper#1]
**Note Push Motor Home 복귀시 PI센서 입인량 커서 프레임 접촉 소음발생**

![image](https://user-images.githubusercontent.com/118319968/202058878-2a006142-14ac-4fb2-b7c7-27a4bee53f15.png)

**Comment by squallryu** [comment]
내용 확인 했습니다. 원인 검토 후 정보 공유 하겠습니다.

**Comment by squallryu** [comment]
[sample.xlsx](https://github.com/ryujunsang/K6_Strapper/files/10017281/sample.xlsx)
첨부한 sample 문서의 **test항목** 확인하시면 해당 문제 해결에 도움이 되실 것 같습니다. 참고하세요.

**Comment by ryujunsang** [comment]
[sample.xlsx](https://github.com/ryujunsang/K6_Strapper/files/10017303/sample.xlsx)
문제 해결에 참고 하실 **사양서** 첨부 했습니다. 수고하세요.

**Comment by ryujunsang** [comment]
첨부해 주신 문서 확인 하여 해당 문제점 원인 확인 하였습니다.
**원인: 최종 가감속 테이블 사양 미적용** 
테스트롬 (rev1234) 를 발행하여 현재 평가기에서 확인 중 입니다.

**Comment by squallryu** [comment]
첨부해 주신 문서 확인 하여 해당 문제점 원인 확인 하였습니다.
**원인: 최종 가감속 테이블 사양 미적용** 
테스트롬 (rev1234) 를 발행하여 현재 평가기에서 확인 중 입니다.

**Comment by ryujunsang** [comment]
테스트롬 결과 확인 했습니다.
해당 테스트롬 정식 릴리즈 하여 **평가팀 검증 평가 의뢰** 부탁드립니다.

**Comment by ryujunsang** [comment]
**평가팀 검증 평가 결과 정상 대책 반영된 것으로 확인** 됩니다. 
해당 이슈는 Close 하겠습니다.

**Comment by ryujunsang** [comment]
**평가팀 검증 평가 결과 정상 대책 반영된 것으로 확인** 됩니다. 
해당 이슈는 Close 하겠습니다.
